import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/layout/AppSidebar";
import AppBreadcrumbs from "@/components/layout/AppBreadcrumbs";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex min-h-svh">
            <AppSidebar />
            <SidebarInset>
              <div className="border-b h-12 flex items-center gap-2 px-4">
                <SidebarTrigger />
                <span className="font-medium">SimTech Email Signature</span>
              </div>
              <div className="px-6 pt-4">
                <AppBreadcrumbs />
              </div>
              <div className="p-6">{children}</div>
            </SidebarInset>
          </div>
          </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
